### ISSUE TITLE
Entregas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Capita-C#100]
**Descrição da Tarefa**

**Métodos de Desenvolvimento de Software**
por favor, criem uma outra página específica para esse material. 

Sugestões:

- Deixem aqui, apenas os vídeos
- Coloquem aqui, os links das outras páginas onde as entregas estão detalhadas. Ou seja: entrega 1: link para o Visão, etc,. Entrega 2: link para esse material, etc..

**Fonte**
(https://mdsreq-fga-unb.github.io/2022.1-Capita-C/entregas/)

**Comment by ArthurFerreiraRodrigues** [comment]
Resolvido por mim.
