### ISSUE TITLE
GitPages - Riscos

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Capita-C#102]
**Descrição da Tarefa**
COMO ESTÃO SENDO OU SERÃO GERENCIADOS ESSES RISCOS?

Incluir isso no documento.

**Fonte**
(https://mdsreq-fga-unb.github.io/2022.1-Capita-C/riscos/)

**Comment by ArthurFerreiraRodrigues** [comment]
![image](https://user-images.githubusercontent.com/69909375/180464337-f00ce3b6-9e86-4c66-a893-f6dcc98c7d39.png)
Temos essa coluna na tabela que detalha sobre o Gerenciamento de Riscos. Isso já basta ou seria necessário um texto mais detalhado sobre o gerenciamento de riscos ? @marsicanogeorge

**Comment by marsicanogeorge** [comment]
sim, mas como esses riscos são avaliados? ao final de cada sprint, por exemplo? algum registro dessa avaliação? @ArthurFerreiraRodrigues

**Comment by ArthurFerreiraRodrigues** [comment]
Durante a retrospectiva, será feito uma conversa sobre acontecimentos que tenham impactado o ciclo, tanto positivamente quanto negativamente. Caso haja uma ocorrência (negativa) de algum dos riscos presentes na tabela de riscos ou de algum outro além desses, será gerado no gitpages um relatório constatando o ocorrido, o nível de impacto, a contramedida e a eficácia dela para solucionar o problema. Seria isso o que você estava em dúvida @marsicanogeorge ?

**Comment by marsicanogeorge** [comment]
essas devem ser atividades e resultados previstos no processo @ArthurFerreiraRodrigues

**Comment by ArthurFerreiraRodrigues** [comment]
Irei adicionar então a descrição desse planejamento em https://mdsreq-fga-unb.github.io/2022.1-Capita-C/riscos/
