### ISSUE TITLE
Ciclos

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Capita-C#103]
**Descrição da Tarefa**
a estrutura de ciclos, atual está denotando um ciclo de **desenvolvimento cascata**: requisitos -> análise e design -> implementação... distribuídos em sprints diferentes.

**Fonte**
https://mdsreq-fga-unb.github.io/2022.1-Capita-C/ciclos/

**Comment by ArthurFerreiraRodrigues** [comment]
Resolvido pelo André
