### ISSUE TITLE
RF6 - Cadastrar Lojas; RF13 - Importar dados de bases externas;

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Capita-C#107]
**Código do Requisito**
RF6 - Cadastrar Lojas; RF13 - Importar dados de bases externas; se esses dois requisitos não farão parte do MVP, de onde virão os dados para *visualizar lista de lojas*?

**Comment by ArthurFerreiraRodrigues** [comment]
RF13 foi adicionado no MVP.
