### ISSUE TITLE
Reunião Requisitos - MDS

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Capita-C#109]
**Descrição da Tarefa**

Reunião Requisitos - MDS
a equipe de MDS deveria estar sendo envolvida desde o início do projeto.

- [x] envolver toda a equipe em reuniões com o cliente; ou 
- [x] realizar reuniões com a equipe de MDS sobre o entendimento do negócio, possíveis requisitos, etc.

**Fonte**
(https://mdsreq-fga-unb.github.io/2022.1-Capita-C/reunioes/)

**Comment by augustocrmg** [comment]
Ok, professor sempre tivemos uma conversa ativa por chat, além disso, eles têm acesso e convite às nossas reuniões e também gravamos as reuniões com o cliente sempre que possível para que todos possam ver. No entanto iremos começar a manter ativamente reuniões entre as equipes de REQ e MDS nas quartas às 19h30.

**Comment by marsicanogeorge** [comment]
Isso deve ser uma atividade prevista no processo @augustocrmg

**Comment by ArthurFerreiraRodrigues** [comment]
Adicionado a descrição das reuniões internas na aba de Organização do projeto.

https://mdsreq-fga-unb.github.io/2022.1-Capita-C/org_proj/
