### ISSUE TITLE
Kanban

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-Capita-C#110]
qual a diferenciação entre as colunas FEATURES, REQUISITOS FUNCIONAIS? ambas são requisitos funcionais, em níveis de abstração diferentes.

- [ ] realizar ajustes no kanban: alterar nomenclatura das colunas ou alterar o conteúdo das colunas

**Comment by ArthurFerreiraRodrigues** [comment]
https://github.com/mdsreq-fga-unb/2022.1-Capita-C/issues/112
